version: '3'

services:

  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8008"
    container_name: storefront
    volumes:
      - .:/storefront:z
    ports:
      - "8008:8008"

  network:
    default:

