# Generated by Django 3.1.3 on 2020-11-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default="Sample Book Description"),
            preserve_default=False,
        ),
    ]
