# Generated by Django 3.1.3 on 2020-11-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('regular', 'REGULAR'), ('fiction', 'FICTION'), ('novel', 'NOVEL')], default='regular', max_length=10),
        ),
    ]
