# Generated by Django 3.1.3 on 2020-11-29 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_description'),
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='book',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='returned_at',
        ),
        migrations.AddField(
            model_name='rental',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RentalLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(help_text='Select a book', on_delete=django.db.models.deletion.CASCADE, related_name='rent_history', to='books.book')),
                ('rental', models.ForeignKey(help_text='Select a book', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='rentals.rental')),
            ],
        ),
    ]
