# Generated by Django 3.1.3 on 2020-11-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_auto_20201129_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalline',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
